stages:
  - build

before_script:
  - apk add --update curl
  - curl -L https://github.com/theupdateframework/notary/releases/download/v0.4.3/notary-Linux-amd64 -o notary; chmod +x notary; mv notary /usr/bin
  - mkdir -p ~/.docker/trust/private
  - echo "$NOTARY_KEY" > ~/.docker/trust/private/$KEY_FILENAME.key
  - docker login $DTR_HOST -u $DTR_CI_USERNAME -p $DTR_CI_PASSWORD
  - export DOCKER_CONTENT_TRUST=1
  - export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=$TRUST_REPO_PASSPHRASE

build:
  stage: build
  image: docker
  script:
    - docker build -t $DTR_HOST/demo/lamp-demo:latest .
    - docker push $DTR_HOST/demo/lamp-demo:latest
