version: '3.6'

services:
  app:
    build:
      context: .
      target: base 
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
  db:
    build: ./docker/db/

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: db 
      PMA_USER: db_user
      PMA_PASSWORD: secretPassword
