services:
  app:
    build:
      context: .
      target: base
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
  db:
    build: ./docker/db/
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: db 
      PMA_USER: db_user
      PMA_PASSWORD: secretPassword

volumes:
  mysql-data: