version: '3.1'

services:
  app:
    image: mikesir87/lamp-demo-app
    ports:
      - 80:80
    deploy:
      replicas: 2
  db:
    image: mikesir87/lamp-demo-mysql
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: secretPassword
